name: End-to-end tests
on: [deployment_status]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment_status.state == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: debug
        uses: hmarr/debug-action@master
        env:
          TEST_URL: ${{ github.event.deployment_status.target_url }}
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          spec: cypress/integration/happy.spec.js
          record: true
          env: base_url=${{ github.event.deployment_status.target_url }}
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
